2021-11-01 Guard 2216 throttling errors etsy full inventory sync
skuvault-integrations/etsyAccess pull request #31
Opened 2021-11-01 17:34 UTC by cristianWilliamSV

[GUARD-2216](https://agileharbor.atlassian.net/browse/GUARD-2216)

I wasn't able to reproduce the error since it is a sporadic error, so in discussion with the team, we decided to increase the timeout to 5 mins and do some regression tests

2021-11-01 17:38 UTC, jnewman-sv approved these changes

2021-11-12 19:37 UTC, jlopezskuv approved these changes

2021-11-24 18:52 UTC, maxim-skuvault commented
@cristianWilliamSV , I see that you merged from 'GUARD-2216/VT-5345-combined-release-2'  into this branch: (![image](https://user-images.githubusercontent.com/47125663/143296810-a04a1a61-1a26-4a3d-8643-b96bcb92907e.png)
So now there are two "combined-release" branches:
![image](https://user-images.githubusercontent.com/47125663/143297039-d24bb7b9-ba08-4f57-9206-e2fc4d1009f9.png)
If 'GUARD-2216/VT-5345-combined-release' is now outdated and we'll no longer use it, can we delete it so that there's no confusion going forward? We might have other Etsy changes later that will need to go into the combined branch.

Also, the package version here (1.7.2) doesn't appear to be in NuGet - https://www.nuget.org/packages/etsyAccess/. This will not deploy to environments.

2021-11-24 19:04 UTC, maxim-skuvault requested changes
[Comments earlier](https://github.com/skuvault-integrations/etsyAccess/pull/31#issuecomment-978140200) and Slack discussion

2021-11-24 20:48 UTC, maxim-skuvault approved these changes

2021-12-14 12:02 UTC, nathan-skuvault approved these changes

2022-01-07 19:46 UTC, nathan-newman65190 approved these changes

2022-01-14 03:28 UTC, merged